#include <stdio.h>

/**
 * main - Write a program that prints the first 50 Fibonacci numbers,
 * starting with 0.
 * starting with 0.
 * Return: the last digit of a number
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55,
 * 89. By considering the terms in the Fibonacci sequence whose
 * values do not exceed 4,000,000, write a program that finds and
 * prints the sum of the even-valued terms, followed by a new line.
 */
int main(void)
{
	int theFirst98Fibonacci(void);
	theFirst98Fibonacci();
	return (0);
}

/**
 * theFirst98Fibonacci - Write a program that prints the first
 * 50 Fibonacci numbers,
 * starting with 0.
 * starting with 0.
 * Return: the last digit of a number
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55,
 * 89. By considering the terms in the Fibonacci sequence whose
 * values do not exceed 4,000,000, write a program that finds and
 * prints the sum of the even-valued terms, followed by a new line.
 */
int theFirst98Fibonacci(void)
{
	int count;
	unsigned long current1, current2, next, current1Thousands,
	current2Thousands, nextThousands, carry;


	count = 0;
	current1 = 0;
	current2 = 1;

	for (count = 1; count <= 91; count++)
	{
		next = current1 + current2;
		current1 = current2;
		current2 = next;
		printf("%lu, ", next);
	}

	current1Thousands = current1 % 1000;
	current1 = current1 / 1000;
	current2Thousands = current2 % 1000;
	current2 = current2 / 1000;

	while (count <= 98)
	{
		carry = (current1Thousands + current2Thousands) / 1000;
		nextThousands = (current1Thousands + current2Thousands) - carry * 1000;
		next = (current1 + current2) + carry;
		current1Thousands = current2Thousands;
		current2Thousands = nextThousands;
		current1 = current2;
		current2 = next;

		if (nextThousands >= 100)
			printf("%lu%lu", next, nextThousands);
		else
			printf("%lu0%lu", next, nextThousands);

		if (count != 98)
			printf(", ");

		count++;
	}

	putchar('\n');
	return (0);
}
